export { App } from './App/App';
export { NavBar } from './NavBar/NavBar';
export { HomePage } from './HomePage/HomePage';
export { Footer } from './Footer/Footer';
export { ProductsIndex } from '../components/ProductsIndex/ProductsIndex';
export { Cart } from '../components/Cart/Cart';
export { ProductDetails } from './ProductDetails/ProductDetails';
export { CheckOut } from './CheckOut/CheckOut';
//export { notification } from './Notification/Notification';